"""One Caddy snippet per app in /etc/caddy/orch-apps/<slug>.caddy, imported by the app.severin.io site.

Every change is validated against the whole Caddyfile before the reload; a config Caddy refuses is rolled back and
never applied, so the other sites on the server keep running on the previous config.
"""

from __future__ import annotations

from . import util
from .util import Failed

CADDYFILE = "/etc/caddy/Caddyfile"


def snippet(slug: str, app: dict) -> str:
    port = util.P.share_port
    name = slug.replace("-", "_")
    out = [f"# orch-apps: {slug} ({app['stack']}, {app['access']}), generated by orch-apps-host; do not edit",
           f"redir /{slug} /{slug}/ 308"]
    if app.get("held"):
        out.append(f"handle_path /{slug}/* {{\n\trespond \"This app is stopped.\" 503\n}}")
        return "\n".join(out) + "\n"
    body = []
    if app["access"] == "secret":
        out.append(f"@{name}_token path_regexp ^/{slug}\\.[A-Za-z0-9_-]{{16,64}}/?$")
        out.append(f"handle @{name}_token {{\n\treverse_proxy 127.0.0.1:{port}\n}}")
        body.append(f"\tforward_auth 127.0.0.1:{port} {{\n\t\turi /_auth/app/{slug}\n\t}}")
    if app["stack"] == "static":
        body.append(f"\troot * {util.P.apps / slug / 'current'}\n\tfile_server")
    else:
        body.append(f"\treverse_proxy 127.0.0.1:{app['port']}")
    out.append(f"handle_path /{slug}/* {{\n" + "\n".join(body) + "\n}")
    return "\n".join(out) + "\n"


def service_env() -> dict:
    """Caddy's environment as systemd gives it: other sites may use {$VARS} set only in a drop-in, so validating
    without them would refuse a config the running Caddy accepts."""
    res = util.run(["systemctl", "show", "caddy", "--property=Environment", "--value"], ok=False)
    env = {"PATH": "/usr/local/bin:/usr/bin:/bin", "HOME": "/var/lib/caddy"}
    for item in (res.stdout or "").split():
        key, eq, value = item.partition("=")
        if eq and key.isidentifier():
            env[key] = value
    return env


def apply(slug: str, text: str | None) -> None:
    """Write (or with None remove) the snippet, validate, reload; restore the previous snippet on failure."""
    util.P.caddy.mkdir(parents=True, exist_ok=True)
    path = util.P.caddy / f"{util.check_slug(slug)}.caddy"
    before = path.read_text() if path.exists() else None
    if text == before:
        return
    if text is None:
        path.unlink(missing_ok=True)
    else:
        path.write_text(text)
        path.chmod(0o644)
    res = util.run(["caddy", "validate", "--config", CADDYFILE, "--adapter", "caddyfile"], ok=False,
                   env=service_env())
    if res.returncode != 0:
        if before is None:
            path.unlink(missing_ok=True)
        else:
            path.write_text(before)
        msg = (res.stderr or res.stdout or "").strip().splitlines()[-3:]
        raise Failed("Caddy refused the config, nothing applied: " + " | ".join(msg))
    util.run(["systemctl", "reload", "caddy"])
